FROM ubuntu:latest

RUN curl -LO https://storage.googleapis.com/kubernetes-helm/helm-v2.9.0-linux-amd64.tar.gz && tar xvf helm-v2.9.0-linux-amd64.tar.gz linux-amd64/helm && mv linux-amd64/helm /usr/local/bin/helm && chmod 755 /usr/local/bin/helm && rm -rf helm-v2.9.0-linux-amd64.tar.gz

RUN apt-get update && apt-get install -y make curl unzip apt-transport-https gnupg git

RUN curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
RUN echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | tee -a /etc/apt/sources.list.d/kubernetes.list
RUN apt-get update
RUN apt-get install -y kubectl
