# Default values for app-mono-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: infracloud/app-mono-api
  tag: 04503e4
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 8082

env:
  LOG_LEVEL: debug
  API_PORT: 8082
